### ISSUE TITLE
Assembly errors upon parts update

### ISSUE THREAD

**Issue by ankou29666** [hamish2014/FreeCAD_assembly2#133]
Hi everyone.

I have created an assembly from a few parts, but the problem I am facing is that after modifying a part, updating the assembly often results in errors, I mean plane constraints fancy refer to wrong faces with completely whimsical results.

Please correct me if I'm wrong, but it looks like the constraints makes for example Part003.Face045 match with Part011.Face123. It also looks like the faces are numbered by the order they appear in the Brep files. In other words, these numbering is not quite random, but not quite deterministic either. It looks like pseudo-random. 

The problem is if for example Part011 is modified and Face123 moves to 137th, the constraint remains upon Face123 instead of being updated to Face137.

Is there any trick to solve this kind of issue ?

**Comment by the-snowwhite** [comment]
Hmmm .. base 12 ,?Excused also.On Apr 25, 2017 1:52 PM, ankou29666 <notifications@github.com> wrote:Hi everyone.
I have created an assembly from a few parts, but the problem I am facing is that after modifying a part, updating the assembly often results in errors, I mean plane constraints fancy refer to wrong faces with completely whimsical results.
Please correct me if I'm wrong, but it looks like the constraints makes for example Part003.Face045 match with Part011.Face123. It also looks like the faces are numbered by the order they appear in the Brep files. In other words, these numbering is not quite random, but not quite deterministic either. It looks like pseudo-random.
The problem is if for example Part011 is modified and Face123 moves to 137th, the constraint remains upon Face123 instead of being updated to Face137.
Is there any trick to solve this kind of issue ?

**Comment by BPLRFE** [comment]
It may depend on the Operating system. If using 0.16.6706 64-bit you may get good results
manually replacing your NUMPY-Library like described here:
https://forum.freecadweb.org/viewtopic.php?p=159786#p159786
[It seems a buggy version of NUMPY was compiled with 0.16.6706 on Windows ...]
For german users i made a video showing the process:
https://www.youtube.com/watch?v=u7190e6hP1Q&index=25&list=PLsrwVwvqYb8EZyMnFb7Ogn4yjTZNLTKTB

**Comment by ankou29666** [comment]
KUbuntu 16.10 FC 0.16.6707

**Comment by ankou29666** [comment]
Ok, here's a little example to make it a bit more explicit : 
[test.zip](https://github.com/hamish2014/FreeCAD_assembly2/files/955940/test.zip)
Just unzip it, and open the assembly file and once you click the solver button you will see something like this : 
![screenshot_20170425_191312 jpg](https://cloud.githubusercontent.com/assets/26046205/25398673/22b96d02-29ed-11e7-891b-6788e88a282e.png)
![screenshot_20170425_191331 jpg](https://cloud.githubusercontent.com/assets/26046205/25398672/22b93936-29ed-11e7-8460-49078c4bf33a.png)

Now open the rising profile file, hide the part, edit the sketch, add a circle centered on the axes, and add a 2.1 mm radius constraint. Close the sketch, and toggle back the part to visible.

Get back to the assembly file, and update.
Here it results in this kind of bullshit : 
![screenshot_20170425_191349 jpg](https://cloud.githubusercontent.com/assets/26046205/25398820/9d6a1e84-29ed-11e7-9203-c695ab16636b.png)
![screenshot_20170425_191420 jpg](https://cloud.githubusercontent.com/assets/26046205/25398819/9d694b9e-29ed-11e7-9896-9bfbe2077a62.png)

Constraint which originally bounded left_vertex_01.Face251 to rising_profile_01.Face1 and should not have been modified now bounds to rising_profile_01.Face11 instead.
Constraint which originally bounded left_vertex_01.Face134 to rising_profile_01.Face2 and should not have been modified now bounds to rising_profile_01.Face7 instead.
Constraint which originally bouned left_vertex_01.Face208 to rising_profile_01.Face45 has been correctly updated to rising_profile_01.Face46.

It's really amazing to see how such a minor modification in a part's geometry can break a complete assembly.

**Comment by kbwbe** [comment]
Hello @ankou29666 ,
this behaviour is caused by FreeCAD itself as renumbering vertexes,edges,faces after very small model changes. As constraints of Assembly 2 are referring to these numbers, the constraints will point to false topology after reimport. There will be no change in Assembly 2 to avoid this as nearly impossible.
